name: buildtest

on:
    pull_request:
        paths:
            - 'src/**'
            - 'public/**'
            - 'package.json'
            - 'package-lock.json'
            - 'tsconfig.json'
            - 'tailwind.config.js'
            - '.github/workflows/deploy.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '18.x'
            - name: install
              run: npm ci
            - name: build
              run: npm run build
